/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv ./cloudflare-env.d.ts` (hash: 7ffdec01adac4544291d71b5d76a7383)
interface __BaseEnv_CloudflareEnv {
	BUCKET: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	NEXT_PUBLIC_APP_WEB_SITE_URL: "https://captureflow-private.flindev.workers.dev";
	NEXT_PUBLIC_RECORDING_SITE_URL: "https://captureflow-private.flindev.workers.dev";
	NEXT_PUBLIC_SCREENSHOT_SITE_URL: "https://captureflow-private.flindev.workers.dev";
	NEXT_PUBLIC_MARKETING_SITE_URL: "https://captureflow-private.flindev.workers.dev";
	APP_DEEP_LINK_SCHEME: "captureflow";
	STORAGE_LIMIT_BYTES: "10737418240";
	CAPTUREFLOW_EXTENSION_ID: "filbcachaagapdgnponemllihgldgffp";
	BETTER_AUTH_SECRET: string;
	BOOTSTRAP_SECRET: string;
	BETTER_AUTH_URL: string;
	ALLOW_REGISTRATION: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_APP_WEB_SITE_URL" | "NEXT_PUBLIC_RECORDING_SITE_URL" | "NEXT_PUBLIC_SCREENSHOT_SITE_URL" | "NEXT_PUBLIC_MARKETING_SITE_URL" | "APP_DEEP_LINK_SCHEME" | "STORAGE_LIMIT_BYTES" | "CAPTUREFLOW_EXTENSION_ID" | "BETTER_AUTH_SECRET" | "BOOTSTRAP_SECRET" | "BETTER_AUTH_URL" | "ALLOW_REGISTRATION">> {}
}
