import identity from "./public-key.json";
import { defineConfig } from "wxt";
import tailwindcss from "@tailwindcss/vite";

// The MV3 manifest is generated by WXT into .output/<target>/manifest.json —
// there is no committed manifest.json.
export default defineConfig({
  modules: ["@wxt-dev/module-react"],
  // Tailwind v4 + @heroui/styles back the popup. Content scripts stay on
  // hand-written scoped CSS so nothing heavy is injected into host pages.
  vite: () => ({ plugins: [tailwindcss()] }),
  manifest: ({ browser, mode }) => {
    const isFirefox = browser === "firefox";
    // `wxt dev` and `wxt build --mode development` both count as dev; only a
    // real production build gets the store identity.
    const isDev = mode !== "production";
    /*
     * Origins allowed to post the device token back via runtime.sendMessage.
     * localhost is dev-only: shipping http://localhost/* in a published build
     * would let any localhost page reach the external-message surface.
     */
    const matches = isDev
      ? [
          "https://captureflow-private.flindev.workers.dev/*",
          "http://localhost/*",
        ]
      : ["https://captureflow-private.flindev.workers.dev/*"];
    /*
     * Chrome derives the extension id from this key, so a dev build carrying it
     * loads under the Web Store id and *replaces* an installed CaptureFlow.
     * Omitting it in dev gives the unpacked build its own path-derived id, so
     * both sit side by side — and /auth/callback already accepts any well-formed
     * id outside production, so nothing needs pinning here.
     *
     * The key comes from a gitignored .env.local, and `pnpm zip` sets WXT_NO_KEY
     * so an uploaded package never carries it (clearing WXT_EXT_KEY itself
     * wouldn't work — WXT reloads it from .env.local over anything the shell
     * sets).
     */
    const key = identity.key;
    // Amber plate instead of the blue one, so the dev build is obvious in the
    // toolbar when both are installed.
    const icons = isDev
      ? {
          16: "icon-dev/16.png",
          32: "icon-dev/32.png",
          48: "icon-dev/48.png",
          128: "icon-dev/128.png",
        }
      : undefined;
    return {
      ...(key ? { key } : {}),
      ...(icons ? { icons } : {}),
      // Chrome Web Store ranks the name field heaviest and caps it at 75 chars;
      // description is the store summary, capped at 132.
      name: isDev ? "CaptureFlow (dev)" : "CaptureFlow Private — Flindev",
      description:
        "Open-source screen recorder and screenshot tool. Record your screen or tab, get an instant shareable link, and send it in seconds.",
      // Without this the toolbar tooltip inherits the keyword-laden store name.
      action: {
        default_title: "CaptureFlow",
        ...(icons ? { default_icon: icons } : {}),
      },
      /*
       * `offscreen` (where getDisplayMedia runs) is Chromium-only, so gate it
       * for Firefox. `scripting` + `activeTab` inject the camera/mic permission
       * iframe on demand; activeTab keeps it warning-free (no broad host access).
       */
      permissions: isFirefox
        ? ["storage"]
        : [
            "storage",
            "offscreen",
            "scripting",
            "activeTab",
            // Records the current tab straight from a stream id, with no
            // "Choose what to share" step. Chrome-only.
            "tabCapture",
          ],
      /*
       * Extension-context fetches to the API need host permission to skip
       * CORS/Private-Network-Access checks — Brave otherwise blocks extension
       * frames from reaching localhost in dev. Mirrors the
       * externally_connectable dev/prod split.
       */
      host_permissions: matches,
      // Firefox MV3 lacks web→extension messaging, so omit it there.
      ...(isFirefox ? {} : { externally_connectable: { matches } }),
      // The injected camera bubble, the permission-grant fallback, and the
      // in-page recorder overlay load these extension pages inside a web origin.
      ...(isFirefox
        ? {}
        : {
            web_accessible_resources: [
              {
                resources: ["bubble.html", "permissions.html", "popup.html"],
                matches: ["<all_urls>"],
              },
            ],
          }),
    };
  },
  hooks: {
    /*
     * The recorder opens as an in-page overlay from action.onClicked; an
     * anchored default_popup would swallow the click.
     *
     * The dev tooltip has to be set here too: WXT fills default_title from the
     * popup entrypoint's <title>, overwriting whatever the manifest block said.
     */
    "build:manifestGenerated": (wxt, manifest) => {
      if (!manifest.action) return;
      delete manifest.action.default_popup;
      if (wxt.config.mode !== "production") {
        manifest.action.default_title = "CaptureFlow (dev)";
      }
    },
  },
});
